import { env } from '$lib/env';
import { APP_CONSTANTS } from './constants.js';

const app_config = {
	SESSION_COOKIE_PREFIX: APP_CONSTANTS.SESSION_COOKIE_PREFIX,

	// Application Settings
	APP_NAME: 'Desktop Environment',

	// Email Verification Settings
	EMAIL_VERIFICATION: {
		EXPIRES_IN: env.EMAIL_VERIFICATION_EXPIRES_IN || 86400, // 24 hours in seconds
		REDIRECT_URL_AFTER_VERIFICATION: '/auth/signin',
		REDIRECT_URL_AFTER_RESEND: '/resend-verification',
		MAX_RESEND_ATTEMPTS_PER_HOUR: 3,
		TOKEN_LENGTH: 32,
		CLEANUP_INTERVAL: 3600000 // 1 hour in milliseconds
	},

	// Rate Limiting Configuration
	RATE_LIMITS: {
		EMAIL_VERIFICATION: {
			WINDOW_MS: 300000, // 5 minutes
			MAX_ATTEMPTS: 5,
			SKIP_SUCCESSFUL_REQUESTS: true
		},
		EMAIL_RESEND: {
			WINDOW_MS: 3600000, // 1 hour
			MAX_ATTEMPTS: 3,
			SKIP_SUCCESSFUL_REQUESTS: false
		}
	},

	// Feature Flags
	FEATURES: {
		EMAIL_VERIFICATION_ENABLED: env.VERIFICATION_FEATURE_ENABLED,
		EMAIL_VERIFICATION_NEW_USERS_ONLY: env.VERIFICATION_NEW_USERS_ONLY,
		EMAIL_VERIFICATION_ROLLOUT_PERCENTAGE: env.VERIFICATION_ROLLOUT_PERCENTAGE,
		EMAIL_VERIFICATION_ROLLOUT_START_DATE: env.VERIFICATION_ROLLOUT_START_DATE
			? new Date(env.VERIFICATION_ROLLOUT_START_DATE)
			: new Date('2024-01-01'),
		AUTO_SIGNIN_AFTER_VERIFICATION: env.AUTO_SIGNIN_AFTER_VERIFICATION
	},

	// Security Settings
	SECURITY: {
		REQUIRE_HTTPS_IN_PRODUCTION: true,
		SECURE_COOKIES_IN_PRODUCTION: true,
		SAME_SITE_POLICY: 'strict' as const,
		CSRF_PROTECTION: true,
		RATE_LIMIT_HEADERS: true
	}
};

export const config = { ...env, ...app_config };
